"Enable Wither" = true
"Enable Dragon" = true

[Wither]
	#How difficulty is handled for the Wither. Disabling this "Feature" will disable all the Dragon changes.
	"Enable Difficulty Settings" = true
	#Handles various small features, such as the explosion
	"Enable Misc" = true
	#Bonus Health and Bonus regeneration. The feature even fixes the Wither health bar not updating on spawn.
	"Enable Health" = true
	#Handles the Damage Resistances and Vulnerabilities
	"Enable Resistances & Vulnerabilities" = true
	#Bonus Experience and Drops
	"Enable Rewards" = true
	#Wither will spawn deadly (and tall) Minions
	"Enable Minions" = true
	#Makes the Wither smarter (will no longer try to stand on the player's head ...), attack faster and hit harder
	"Enable Attack" = true

	#How difficulty is handled for the Wither. Disabling this "Feature" will disable all the Dragon changes.
	[Wither."Difficulty Settings"]
		#How much blocks from wither will be scanned for players to check for difficulty
		#Range: > 16
		"Spawn Radius Player Check" = 128
		#If true and there are more players around the Wither, the Wither will have his stats based on the sum of both players difficulty. If false, the Wither stats will be based on the average of the difficulty of the players around
		"Sum Spawned Wither Difficulty" = false
		#The Maximum difficulty (times spawned) reachable by Wither. By default is set to 72 because the Wither reaches the maximum amount of health (1024, capped by Minecraft. Some mods can increase this) after 72 withers spawned.
		#Range: > 1
		"Max Difficulty" = 72
		#How much difficulty will players start with when joining a world? Note that this will apply when the first Wither is spawned so if the player has already spawned one this will not apply.
		#Range: > 0
		"Starting Difficulty" = 0

	#Handles various small features, such as the explosion
	[Wither.Misc]
		#How much explosion power (after the invulnerability) will the Wither gain for each difficulty point. Explosion Radius is capped to 13. Base Wither Explosion Power is 7.0. Setting this to 0 will not increase the Wither Explosion Power.
		#Range: 0.0 ~ 4.0
		"Explosion Power Bonus" = 0.3
		#At this difficulty the Wither Explosion will cause fire. Set to -1 to disable.
		#Range: > -1
		"Explosion Causes Fire at Difficulty" = 8
		#The Wither will no longer wait 1 full second before breaking blocks when he's hit, instead just 0.5s
		"Faster Breaking Blocks" = true
		#The Wither will break even blocks below him when hit.
		"Bigger Breaking Blocks" = true
		#The wither can only be spawned in the Nether.
		#Note that this feature completely disables Wither Skulls from begin placed nearby Soul Sand when not in the Nether or when on the Nether Roof.
		#Requires Minecraft restart.
		"Wither Nether Only" = false

	#Bonus Health and Bonus regeneration. The feature even fixes the Wither health bar not updating on spawn.
	[Wither.Health]
		#Increase Wither's Health by this value per difficulty
		#Range: 0.0 ~ 1.7976931348623157E308
		"Health Bonus per Difficulty" = 10.0
		#Maximum bonus regeneration per second given by "Bonus Regeneration per Difficulty". Set to 0 to disable bonus health regeneration. This doesn't affect the natural regeneration of the Wither (1 Health per Second). It's not recommended to go over 1.0f without mods that adds stronger things to kill the Wither
		#Range: 0.0 ~ 1.7976931348623157E308
		"Maximum Bonus Regeneration" = 2.0
		#How many half hearts will the Wither regen more per difficulty. This doesn't affect the natural regeneration of the Wither (1 Health per Second). (E.g. By default, with 6 Withers spawned, the Wither will heal 1.3 health per second).
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Regeneration per Difficulty" = 0.05

	#Handles the Damage Resistances and Vulnerabilities
	[Wither."Resistances & Vulnerabilities"]
		#Percentage Damage Reduction while the Wither is above half health.
		#Range: 0.0 ~ 1.0
		"Damage reduction per Difficulty above half health" = 0.01
		#Cap for 'Damage reduction per Difficulty above half health'
		#Range: 0.0 ~ 1.0
		"Max Damage reduction per Difficulty before half health" = 0.15
		#Percentage Damage Reduction as the Wither drops below half health.
		#Range: 0.0 ~ 1.0
		"Damage reduction per Difficulty below half health" = 0.02
		#Cap for 'Damage Reduction per Difficulty below half health'
		#Range: 0.0 ~ 1.0
		"Max Damage reduction per Difficulty below half health" = 0.36
		#Bonus magic damage based off missing health. 150 means that every 150 missing health the damage will be amplified by 100%. E.g. The difficulty = 0 Wither (with 300 max health) is at half health (so it's missing 150hp), on magic damage he will receive 'magic_damage * (missing_health / magic_damage_bonus + 1)' = 'magic_damage * (150 / 150 + 1)' = 'magic_damage * 2'.
		#Range: 0.0 ~ 1024.0
		"Magic Damage Bonus" = 200.0

	#Bonus Experience and Drops
	[Wither.Rewards]
		#How much more experience (percentage) will Wither drop per Difficulty. The percentage is additive (e.g. with this set to 10%, 7 withers spawned = 70% more experience)
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Experience per Difficulty" = 20.0
		#A list of drops for the Withers. Entry format: item,amount,difficulty_required,chance,difficulty_mode,chance_mode
		#item: item id
		#amount: amount
		#difficulty_required: the amount of difficulty required for the item to drop, works differently based on mode
		#chance: chance for the drop to happen, between 0 and 1
		#difficulty_mode:
		#* MINIMUM: will try to drop the item when the difficulty matches or is higher
		#* PER_DIFFICULTY: will try to drop the item once per difficulty (e.g. at difficulty 10, difficulty required 3, there is the chance to drop the item, trying 7 times)
		#chance_mode:
		#* FLAT: chance is the percentage chance for the item to drop if the difficulty criteria matches
		#* SCALING: each point of difficulty >= 'difficulty to drop the item' will be multiplied by the chance (e.g. chance 2% and difficulty 10, difficulty required 5, chance to drop the item will be chance * (difficulty - difficulty_required + 1) = 2% * (10 - 5 + 1) = 12%)
		#By default Withers have 2% chance per difficulty >= 2 to drop 1 shard + 4% chance per difficulty >= 4 to drop 2 shards + 8% chance per difficulty >= 8 to drop 4 shards.
		Drops = ["progressivebosses:nether_star_shard,1,1,0.16,PER_DIFFICULTY,FLAT"]

	#Wither will spawn deadly (and tall) Minions
	[Wither.Minions]
		#At which difficulty the Wither starts spawning Minions
		#Range: > 0
		"Minion at Difficulty" = 1
		#As the Wither starts spawning Minions, every how much difficulty the Wither will spawn one more Minion
		#Range: > 0
		"Bonus Minion Every Difficulty" = 2
		#Maximum Minions spawned by the Wither
		#Range: > 0
		"Max Minions Spawned" = 6
		#Maximum amount of Minions that can be around the Wither in a 16 block radius. After this number is reached the Wither will stop spawning minions. Set to 0 to disable this check
		#Range: > 0
		"Max Minions Around" = 20
		#Minimum ticks (20 ticks = 1 seconds) after Minions can spwan.
		#Range: > 0
		"Minimum Cooldown" = 240
		#Maximum ticks (20 ticks = 1 seconds) after Minions can spwan.
		#Range: > 0
		"Maximum Cooldown" = 480
		#Min and Max cooldowns are multiplied by this value when the Wither drops below half health. Set to 1 to not change the cooldown when the wither's health drops below half.
		#Range: 0.0 ~ 1.7976931348623157E308
		"Cooldown Multiplier Below Half Health" = 0.6
		#Percentage bonus speed per difficulty. (0.01 means 1%)
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Movement Speed Per Difficulty" = 0.004
		#Wither Minions will die when the Wither that spawned them dies.
		"Kill Minions on Wither Death" = true

		[Wither.Minions.Equipment]
			#Wither Minions will spawn with a Stone Sword
			"Has Sword" = true
			#Chance for the Wither Minion to spawn with a bow when Wither's above Half Health
			#Range: 0.0 ~ 1.0
			"Bow Chance Over Half Health" = 0.6
			#Chance for the Wither Minion to spawn with a bow when Wither's below Half Health
			#Range: 0.0 ~ 1.0
			"Bow Chance Below Half Health" = 0.08
			#Chance for the Wither Minion Sword / Bow to be enchanted with Sharpness / Power. Note that every 100% chance adds one guaranteed level of the enchantment, while the remaining chance dictates if one more level will be added.
			#Range: 0.0 ~ 1.7976931348623157E308
			"Power / Sharpness Chance" = 0.0625
			#Chance for the Wither Minion Sword / Bow to be enchanted with Knockback / Punch. Note that every 100% chance adds one guaranteed level of the enchantment, while the remaining chance dictates if one more level will be added.
			#Range: 0.0 ~ 1.7976931348623157E308
			"Punch / Knockback Chance" = 0.04

	#Makes the Wither smarter (will no longer try to stand on the player's head ...), attack faster and hit harder
	[Wither.Attack]
		#If the AI changes should be applied to the first wither spawned too.
		"Apply to Vanilla Wither" = true
		#Chance every time the Wither takes damage to start a charge attack. The chance is doubled when the Wither is below half health.
		#Range: 0.0 ~ 1.0
		"Charge Attack Chance" = 0.015
		#Chance (per difficulty) every time the Wither takes damage to start a barrage attack. The chance is doubled when the Wither is below half health
		#Range: 0.0 ~ 1.0
		"Barrage Attack Chance" = 0.002
		#Max Chance for the barrage attack. The max chance is doubled when the Wither is below half health
		#Range: 0.0 ~ 1.0
		"Max Barrage Attack Chance" = 0.05
		#Percentage bonus damage dealt by the Wither.
		#Range: 0.0 ~ 1.7976931348623157E308
		"Increased Damage" = 0.02

		#Wither Skull Changes
		[Wither.Attack.Skulls]
			#Wither Skull Projectiles speed will be multiplied by this value.
			#Range: 0.0 ~ 1.7976931348623157E308
			"Skull Velocity Multiplier" = 2.5

		#Attack Speed Changes
		[Wither.Attack."Attack Speed"]
			#Every how many ticks (20 ticks = 1 seconds) the middle head will fire a projectile to the target.
			#Range: > 0
			"Attack Interval" = 40
			#The middle head will attack faster (up to 40% of the attack speed) the nearer the target is to the Wither.
			"Increase Attack Speed when Near" = true

[Dragon]
	#How difficulty is handled for the Dragon. Disabling this "Feature" will disable all the Dragon changes.
	"Enable Difficulty Settings" = true

	#How difficulty is handled for the Dragon. Disabling this "Feature" will disable all the Dragon changes.
	[Dragon."Difficulty Settings"]
		#If true and there are more players around the Dragon, she will have his stats based on the sum of both players' difficulty. If false, the Dragon stats will be based on the average of the difficulty of the players around.
		"Sum Killed Dragons Difficulty" = false
		#The Maximum difficulty (times killed) reachable by Ender Dragon. By default is set to 82 because the Ender Dragon reaches the maximum amount of health (1024, handled by Minecraft. Some mods can increase this) after 82 Dragons killed.
		#Range: > 1
		"Max Difficulty" = 82
		#How much difficulty will players start with when joining a world?  Note that this will apply when the first Dragon is killed so if the player has already killed one this will not apply.
		#Range: > 0
		"Starting Difficulty" = 0

